# Exploratory Data Analysis (EDA)

In [18]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

## Завантаження та обробка даних

In [19]:
df = pd.read_csv('data/tested.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [20]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [21]:
df["Age"] = df["Age"].fillna(int(df["Age"].mean()))
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [22]:
x = df[["Pclass", "Sex", "Age", "SibSp", "Parch", "Fare", "Embarked"]]
y = df["Survived"]
x["Sex"] = LabelEncoder().fit_transform(x["Sex"])
x["Embarked"] = LabelEncoder().fit_transform(x["Embarked"])

C:\Users\avhrs\AppData\Local\Temp\ipykernel_22032\4287624111.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x["Sex"] = LabelEncoder().fit_transform(x["Sex"])
C:\Users\avhrs\AppData\Local\Temp\ipykernel_22032\4287624111.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x["Embarked"] = LabelEncoder().fit_transform(x["Embarked"])

In [23]:
x = pd.get_dummies(x, columns=["Embarked"])
x

,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_0,Embarked_1,Embarked_2
0,3,1,34.5,0,0,7.8292,False,True,False
1,3,0,47.0,1,0,7.0000,False,False,True
2,2,1,62.0,0,0,9.6875,False,True,False
3,3,1,27.0,0,0,8.6625,False,False,True
4,3,0,22.0,1,1,12.2875,False,False,True
...,...,...,...,...,...,...,...,...,...
413,3,1,30.0,0,0,8.0500,False,False,True
414,1,0,39.0,0,0,108.9000,True,False,False
415,3,1,38.5,0,0,7.2500,False,False,True
416,3,1,30.0,0,0,8.0500,False,False,True
417,3,1,30.0,1,1,22.3583,True,False,False

In [24]:
x_train, x_val, y_train, y_val = train_test_split(x, y, test_size=0.2, random_state=42)

scaler = MinMaxScaler()
x_train = scaler.fit_transform(x_train)
x_val = scaler.transform(x_val)
x_train

array([[0.5       , 1.        , 0.41852782, ..., 0.        , 0.        ,
        1.        ],
       [0.5       , 1.        , 0.3128056 , ..., 0.        , 0.        ,
        1.        ],
       [0.5       , 1.        , 0.39209726, ..., 0.        , 1.        ,
        0.        ],
       ...,
       [0.        , 1.        , 0.60354169, ..., 1.        , 0.        ,
        0.        ],
       [0.5       , 1.        , 0.3128056 , ..., 0.        , 0.        ,
        1.        ],
       [1.        , 1.        , 0.39209726, ..., 0.        , 1.        ,
        0.        ]])

In [25]:
x_train.to_csv("data/x_train.csv", index=False)
x_val.to_csv("data/x_val.csv", index=False)
#x_test.to_csv("data/processed_data/x_test.csv", index=False)

y_train.to_csv("data/y_train.csv", index=False)
y_val.to_csv("data/y_val.csv", index=False)
#y_test.to_csv("data/processed_data/y_test.csv", index=False)

AttributeError: 'numpy.ndarray' object has no attribute 'to_csv'